language: node_js
node_js:
  - v8
  - v7
  - v6
  - v5
  - v4
cache:
  directories:
    - node_modules
install:
  - npm install i2c-bus --ignore-scripts
  - npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm prune
after_success:
  - npm run report-coverage
  - npm run build
  - npm run semantic-release
  - npm run build-docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/motor-hat/1.0.0-semanticrelease
  on:
    branch: 2.0.0
